CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255)
);

CREATE TABLE habits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    icon VARCHAR(255),
    frequency VARCHAR(255),
    active BOOLEAN DEFAULT TRUE,
    owner_id BIGINT,
    CONSTRAINT fk_habit_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE habit_done_dates (
    habit_id BIGINT NOT NULL,
    done_date DATE,
    CONSTRAINT fk_done_dates_habit FOREIGN KEY (habit_id) REFERENCES habits(id)
);

CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    description VARCHAR(255),
    active BOOLEAN DEFAULT TRUE,
    percent_off INTEGER DEFAULT 0
);
